# Generated by Django 4.0.4 on 2022-05-25 23:24

from django.conf import settings
import django.contrib.auth.mixins
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.views.generic.edit


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('AppFulana', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NuevoPosteo',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=(django.contrib.auth.mixins.LoginRequiredMixin, django.views.generic.edit.CreateView, 'auth.user'),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='posteo',
            name='likes',
            field=models.ManyToManyField(related_name='blog_posteo', to=settings.AUTH_USER_MODEL),
        ),
    ]
