# Generated by Django 4.0.4 on 2022-05-26 02:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppFulana', '0004_remove_posteo_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='posteo',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
